# Generated by Django 4.0.4 on 2022-04-18 01:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_rename_book_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None), size=None),
        ),
    ]
