# Generated by Django 4.0.4 on 2022-04-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_alter_band_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='year_formed',
            field=models.PositiveIntegerField(),
        ),
    ]
