# Generated by Django 4.0.4 on 2022-04-21 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('labels', '0001_initial'),
        ('bands', '0006_band_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.label'),
        ),
        migrations.AlterField(
            model_name='band',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member'),
        ),
    ]
