# Generated by Django 4.0.4 on 2022-04-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('labels', '0001_initial'),
        ('bands', '0007_band_label_alter_band_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='supporting_members',
            field=models.ManyToManyField(blank=True, related_name='supported', to='members.member'),
        ),
        migrations.AlterField(
            model_name='band',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_bands', to='labels.label'),
        ),
        migrations.AlterField(
            model_name='band',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starred', to='members.member'),
        ),
    ]
