# Generated by Django 4.0.4 on 2022-04-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_band_supporting_members_alter_band_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='member',
            new_name='leader',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='supporting_members',
            new_name='members',
        ),
    ]
